apiVersion: v1
kind: Service
metadata:
  name: restservice
  namespace: default
  labels:
    app: restservice
spec:
  selector:
    app: restservice
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: NodePort